name: wavesim
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  get_it: ^9.2.0
  http: ^1.6.0
  jaspr: ^0.21.7
  jaspr_router: ^0.8.0
  live_cells_core: ^1.4.0
  live_cells_jaspr: ^0.1.2
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.10.4
  jaspr_web_compilers: ^4.3.2+1
  jaspr_builder: ^0.21.7
  jaspr_lints: ^0.6.0
  lints: ^5.0.0
  live_cell_extension: ^0.7.1

jaspr:
  mode: static

